---
title: "Recommender Systems"
author: "Christina Kasman"
output: html_document
---
Recommender Systems: Pinterest

Pinterest is a web and mobile application that allows users to explore and collect new ideas and information.

1. Who are your target users?
Those looking to disover and save ideas. Each idea is represented by a pin which includes an image, description, and link back to the original online source. There are over 30 billion pins on Pinterest. The user can repin a pin to their own personal boards.

2.What are their key goals?
Those who use pinterest create boards to gain inspiration on a specific subject and gather information or ideas on their own personal boards. This can be anything from "pinning" recipes to DIY projects to just collection pictures that one likes.

3.How can you help them accomplish these goals?
Pinterest helps users accomplish their goals by recommending pins that are relevant and similar to their interests.These relevant pins are displayed on a personalized home feed on the website.

Reverse Engineering:
Pinterest uses a machine learning format called "Pinnability." This estimates relevance scores of how likely a pinner will interact with a pin.They use training data accumulated from how pinners historically interact with the their home feed.If a pinner takes a positive action with a pin (repin or like it) it is recorded as a positive response. This along with how new a pin is will determine if it appears on the home feed and where on the home feed (at the top or bottom based on if it is a new pin vs an older pin).

Include specific recommendations about how to improve the site's recommendation capabilities going forward:

The site can improve their recommendations by including more broad recommendations based on topics rather than individual pins. For example, if you have many pins related vegetarian recipes they may also recommend pins related to healthy lifestyle.
They can also show recommendations based on "those who pinned a, also pinned b." This will help to broaden and discover new interests.
